#!/usr/bin/env python3
"""
One-time batch fix: add frontmatter to wiki/concepts/ and wiki/articles/ files
that were generated by wiki_compiler.py without frontmatter.

Safe: skips files already starting with '---', preserves all existing content.
"""
import re, os, sys
from pathlib import Path
from datetime import datetime

VAULT = Path(r"D:\Obsidian\vault")
TODAY = datetime.now().strftime("%Y-%m-%d")

def parse_title_domain(text):
    """Extract title from first '# Title' and domain from '**Domain**: XXX'."""
    title = None
    m = re.search(r'^# (.+?)$', text, re.MULTILINE)
    if m:
        title = m.group(1).strip()
    domain = "Unknown"
    m = re.search(r'\*\*Domain\*\*:\s*(.+?)$', text, re.MULTILINE)
    if m:
        domain = m.group(1).strip()
    compiled_date = None
    m = re.search(r'\*\*Compiled\*\*:\s*(\d{4}-\d{2}-\d{2})', text)
    if m:
        compiled_date = m.group(1)
    return title, domain, compiled_date

def add_frontmatter(content, title, domain, file_type, compiled_date=None):
    """Prepend YAML frontmatter to content."""
    fm_lines = ["---"]
    fm_lines.append(f'title: "{title}"' if title else "# missing title")
    fm_lines.append(f"type: {file_type}")
    fm_lines.append(f"domain: {domain}")
    if compiled_date:
        fm_lines.append(f"created: {compiled_date}")
    else:
        fm_lines.append(f"created: {TODAY}")
    fm_lines.append("auto: true")
    fm_lines.append("---")
    fm_lines.append("")  # blank line after frontmatter
    return "\n".join(fm_lines) + content

def process_directory(subdir, file_type):
    path = VAULT / "wiki" / subdir
    if not path.exists():
        print(f"  SKIP: {path} does not exist")
        return 0, 0

    files = sorted(path.glob("*.md"))
    fixed = 0
    skipped = 0
    for f in files:
        original = f.read_text(encoding="utf-8", errors="ignore")
        if original.startswith("---"):
            skipped += 1
            continue
        title, domain, compiled_date = parse_title_domain(original)
        new_content = add_frontmatter(original, title, domain, file_type, compiled_date)
        f.write_text(new_content, encoding="utf-8")
        fixed += 1
        if fixed <= 3:
            print(f"  [sample] {f.name}  domain={domain}")
    return fixed, skipped

def main():
    print(f"=== Add Frontmatter Batch Fix ({TODAY}) ===\n")

    c_fixed, c_skipped = process_directory("concepts", "concept")
    print(f"  wiki/concepts/: fixed={c_fixed}, already-ok={c_skipped}\n")

    a_fixed, a_skipped = process_directory("articles", "article-summary")
    print(f"  wiki/articles/: fixed={a_fixed}, already-ok={a_skipped}\n")

    total = c_fixed + a_fixed
    total_skip = c_skipped + a_skipped
    print(f"=== Done: {total} fixed, {total_skip} already had frontmatter ===")

if __name__ == "__main__":
    main()
