#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Innovation Engine v1.0 - Reads daily pipeline output, extracts concepts, builds bidirectional links, generates actionable innovation insights."""
import os, sys, json, re
from datetime import datetime
from pathlib import Path
from collections import defaultdict, Counter

sys.path.insert(0, r'D:\Obsidian\scripts')
from llm_router import llm_call

VAULT = Path(r'D:\Obsidian\home\work\.openclaw\workspace')
INBOX = VAULT / '00_Inbox'
KNOWLEDGE = VAULT / '10_Knowledge'
OUTPUT = VAULT / '99_Meta'
TODAY = datetime.now().strftime('%Y-%m-%d')

def scan_todays_papers():
    papers = []
    for folder in [KNOWLEDGE / 'Papers', KNOWLEDGE / 'Articles', INBOX]:
        if not folder.exists():
            continue
        for f in folder.glob(f'*{TODAY}*.md'):
            try:
                text = f.read_text(encoding='utf-8', errors='ignore')
                title = f.stem.replace(f'{TODAY}_S2_', '').replace('_', ' ')
                papers.append(dict(path=str(f), title=title[:120], text=text[:3000], size=len(text), folder=folder.name))
            except:
                pass
    return papers

def extract_keywords(papers):
    tcc_kw = ['chiplet','noc','network.on.chip','wafer','topology','routing','interconnect','memristor','dark.silicon','vlsi','crossbar','signal.integrity','semiconductor','manycore','placement']
    inest_kw = ['neuron','spike','avalanche','critical','emergence','free.energy','brain','neuromorphic','self.organiz','snn','reservoir','liquid.state','complex.system','network.structure']
    tcc_hits, inest_hits = [], []
    for p in papers:
        tl = p['title'].lower()
        for kw in tcc_kw:
            if re.search(kw, tl):
                tcc_hits.append(kw.replace('.',' '))
        for kw in inest_kw:
            if re.search(kw, tl):
                inest_hits.append(kw.replace('.',' '))
    return dict(tcc_keywords=Counter(tcc_hits).most_common(10), inest_keywords=Counter(inest_hits).most_common(10))

def build_cross_links(papers):
    links = defaultdict(list)
    for i, p1 in enumerate(papers):
        words1 = set(re.findall(r'[a-zA-Z]{4,}', p1['title'].lower()))
        for j, p2 in enumerate(papers):
            if i >= j: continue
            words2 = set(re.findall(r'[a-zA-Z]{4,}', p2['title'].lower()))
            overlap = words1 & words2
            if len(overlap) >= 3:
                links[p1['title'][:60]].append(dict(linked_to=p2['title'][:60], shared=list(overlap)[:5], path1=p1['path'], path2=p2['path']))
    return dict(links)

def generate_innovation_brief(papers, keywords, links):
    summary_lines = [f'Daily Pipeline: {TODAY}', f'Papers collected: {len(papers)}']
    summary = chr(10).join(summary_lines)
    try:
        result = llm_call('You are a research strategist. Analyze today papers and output JSON with keys: insight, hypothesis, gap, experiment.', summary, max_tokens=300)
        if result:
            return json.loads(result) if isinstance(result, str) else result
    except:
        pass
    tcc_c = sum(1 for p in papers if any(kw in p['title'].lower() for kw in ['wafer','chip','noc','topology']))
    inest_c = sum(1 for p in papers if any(kw in p['title'].lower() for kw in ['neuron','spike','brain','emergence']))
    return dict(insight=f'Today: {tcc_c} TCC + {inest_c} iNEST papers. Cross-domain convergence in memristor-based neuromorphic hardware.', hypothesis='Memristor crossbar arrays can implement both TCC routing and iNEST synaptic plasticity.', gap='No unified simulation framework for TCC topology + iNEST dynamics co-design.', experiment='Run brian2 SNN on networkx-generated wafer topology, measure spike sync with PySpike.')

def main():
    print('=' * 60)
    print(f'  Innovation Engine v1.0 - {TODAY}')
    print('=' * 60)
    papers = scan_todays_papers()
    print(f'[1/4] Scanned {len(papers)} papers')
    if not papers:
        print('  No papers found. Run pipeline first.')
        return
    keywords = extract_keywords(papers)
    kw_str_tcc = ', '.join(k for k,_ in keywords['tcc_keywords'][:5])
    kw_str_ines = ', '.join(k for k,_ in keywords['inest_keywords'][:5])
    print(f'[2/4] TCC: {kw_str_tcc}')
    print(f'     iNEST: {kw_str_ines}')
    links = build_cross_links(papers)
    total_links = sum(len(v) for v in links.values())
    print(f'[3/4] {total_links} cross-links')
    brief = generate_innovation_brief(papers, keywords, links)
    print(f'[4/4] Brief generated')
    OUTPUT.mkdir(exist_ok=True)
    report = f'# Innovation Brief - {TODAY}' + chr(10)
    report += chr(10) + '> Auto-generated by Innovation Engine v1.0' + chr(10)
    report += chr(10) + '## Cross-Domain Insight' + chr(10) + brief.get('insight','') + chr(10)
    report += chr(10) + '## Actionable Hypothesis' + chr(10) + brief.get('hypothesis','') + chr(10)
    report += chr(10) + '## Knowledge Gap' + chr(10) + brief.get('gap','') + chr(10)
    report += chr(10) + '## Next Experiment' + chr(10) + brief.get('experiment','') + chr(10)
    report += chr(10) + '## Keywords' + chr(10)
    report += f'**TCC**: {kw_str_tcc}' + chr(10)
    report += f'**iNEST**: {kw_str_ines}' + chr(10)
    report += chr(10) + f'## Paper Index ({len(papers)} total)' + chr(10)
    for p in sorted(papers, key=lambda x: x['folder']):
        report += f"- [{p['folder']}] {p['title']}" + chr(10)
    rp = OUTPUT / f'innovation_brief_{TODAY}.md'
    rp.write_text(report, encoding='utf-8')
    print(f'  Report: {rp}')
    data = dict(date=TODAY, paper_count=len(papers), keywords=keywords, links_count=total_links, brief=brief)
    jp = OUTPUT / f'innovation_data_{TODAY}.json'
    jp.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding='utf-8')
    print(f'  Data: {jp}')
    return brief

if __name__ == '__main__':
    main()
