"""
Daily data update script for TCC x iNEST dashboard.
Safely updates data.js ONLY - never touches index.html.

Usage: python update_daily.py
  - Adds today's entry if not present
  - Preserves all existing entries
  - Updates DATA_VERSION for cache busting
"""
import json, os
from datetime import date

DATA_JS = r"D:\Obsidian\home\work\.openclaw\workspace\dashboard\data.js"

def read_daily():
    """Read daily data from data.js, returns (version, daily_list)"""
    with open(DATA_JS, "r", encoding="utf-8") as f:
        content = f.read()
    # Extract DATA_VERSION
    import re
    ver_match = re.search(r'DATA_VERSION\s*=\s*"([^"]+)"', content)
    version = ver_match.group(1) if ver_match else "0"
    # Extract DASHBOARD_DAILY
    start = content.find("var DASHBOARD_DAILY = ")
    if start < 0:
        return version, []
    json_str = content[start + len("var DASHBOARD_DAILY = "):]
    if json_str.endswith(";"):
        json_str = json_str[:-1]
    daily = json.loads(json_str)
    return version, daily

def write_daily(daily_list, version=None):
    """Write daily data back to data.js"""
    if version is None:
        version = date.today().isoformat()
    import time
    ver = f"{date.today().isoformat()}v{int(time.time()) % 100000}"
    content = f"""// DAILY DATA - Auto-generated by update_daily.py
// Last updated: {date.today().isoformat()}
var DATA_VERSION = "{ver}";
var DASHBOARD_DAILY = {json.dumps(daily_list, ensure_ascii=False)};"""
    with open(DATA_JS, "w", encoding="utf-8", newline="") as f:
        f.write(content)
    return ver

def add_today(daily_list, progress_items, plan_items):
    """Add or update today's entry"""
    today = date.today().isoformat()
    # Check if today already exists
    for i, d in enumerate(daily_list):
        if d["date"] == today:
            daily_list[i]["progress"] = progress_items
            daily_list[i]["plan"] = plan_items
            daily_list[i]["type"] = "today"
            return daily_list, "updated"
    # Insert new entry at the beginning
    new_entry = {
        "date": today,
        "type": "today",
        "progress": progress_items,
        "plan": plan_items
    }
    daily_list.insert(0, new_entry)
    return daily_list, "added"

# Example template for progress items
# Each item: {"text": "...", "dot": "done|ongoing|plan", "dim": "TCC|iNEST|TCC+iNEST"}
PROGRESS_TEMPLATE = [
    {"text": "【描述当日进展1】", "dot": "done", "dim": "TCC+iNEST"},
    {"text": "【描述当日进展2】", "dot": "done", "dim": "TCC+iNEST"},
]

PLAN_TEMPLATE = [
    {"text": "[TCC] 从节点中心到拓扑中心：计算范式根本转变的理论框架", "dot": "plan", "dim": "TCC"},
    {"text": "[TCC] TCC 拓扑中心计算引擎开发", "dot": "plan", "dim": "TCC"},
    {"text": "[iNEST] iNEST 复杂网络涌现智能技术白皮书", "dot": "plan", "dim": "iNEST"},
    {"text": "[TCC+iNEST] 论文与专利撰写推进", "dot": "plan", "dim": "TCC+iNEST"},
]

if __name__ == "__main__":
    ver, daily = read_daily()
    print(f"Current version: {ver}")
    print(f"Daily entries: {len(daily)}")
    for d in daily:
        prog_n = len(d.get("progress", []))
        plan_n = len(d.get("plan", []))
        print(f"  {d['date']} [{d['type']}] progress:{prog_n} plan:{plan_n}")
    
    # Add today with template (edit the templates above for real content)
    daily, action = add_today(daily, PROGRESS_TEMPLATE, PLAN_TEMPLATE)
    new_ver = write_daily(daily)
    print(f"\nToday's entry {action}")
    print(f"New version: {new_ver}")
