"""
TCC x iNEST R&D Autopilot - Intelligent Daily Planner
======================================================
Reads current entries state, identifies three parallel work streams
(Paper/Patent/Guide), and auto-generates today's plan based on
continuity of active items.

Three Streams:
  1. 论文 (Papers + Monographs)
  2. 专利 (Patents)
  3. 项目指南策划 (Project Guides + White Papers)

Usage: python update_daily.py [--dry-run]
"""
import json, re, os, sys
from datetime import date, timedelta
from collections import Counter

INDEX_HTML = r"D:\Obsidian\home\work\.openclaw\workspace\dashboard\index.html"
DATA_JS = r"D:\Obsidian\home\work\.openclaw\workspace\dashboard\data.js"

# ─── Data Readers ───
def read_entries():
    """Read all entries from index.html DEFAULT_DATA"""
    with open(INDEX_HTML, "r", encoding="utf-8") as f:
        html = f.read()
    dd_s = html.find("var DEFAULT_DATA = ")
    dd_e = html.find("};", dd_s) + 2
    data_str = html[dd_s + len("var DEFAULT_DATA = "):dd_e - 1]
    m = re.search(r"\{(.+)\}", data_str)
    return json.loads(m.group(0))["entries"]

def read_daily():
    """Read daily data from data.js"""
    with open(DATA_JS, "r", encoding="utf-8") as f:
        content = f.read()
    ver_match = re.search(r'DATA_VERSION\s*=\s*"([^"]+)"', content)
    version = ver_match.group(1) if ver_match else "0"
    start = content.find("var DASHBOARD_DAILY = ")
    if start < 0:
        return version, []
    json_str = content[start + len("var DASHBOARD_DAILY = "):]
    if json_str.endswith(";"):
        json_str = json_str[:-1]
    return version, json.loads(json_str)

def write_daily(daily_list):
    """Write daily data back to data.js"""
    import time
    ver = f"{date.today().isoformat()}v{int(time.time()) % 100000}"
    content = f"""// DAILY DATA - Auto-generated by update_daily.py
// Last updated: {date.today().isoformat()}
var DATA_VERSION = "{ver}";
var DASHBOARD_DAILY = {json.dumps(daily_list, ensure_ascii=False)};"""
    with open(DATA_JS, "w", encoding="utf-8", newline="") as f:
        f.write(content)
    return ver

# ─── Intelligence Engine ───
def analyze_entries(entries):
    """Analyze entries and return structured stream data"""
    # Active statuses (not completed/done/finished)
    ACTIVE_STATUSES = {"撰写中", "进行中", "开发中", "测试中", "验证中", "探索中",
                       "资料整理", "持续撰写", "持续更新"}

    streams = {
        "论文": {"items": [], "active": [], "top": []},
        "专利": {"items": [], "active": [], "top": []},
        "项目指南策划": {"items": [], "active": [], "top": []}
    }

    for e in entries:
        cat = e["cat"]
        if cat not in streams:
            continue
        streams[cat]["items"].append(e)
        if e["status"] in ACTIVE_STATUSES:
            streams[cat]["active"].append(e)

    # For each stream, pick top 2-3 by priority (高 first)
    for name in streams:
        active = streams[name]["active"]
        high = [a for a in active if a["priority"] == "高"]
        med = [a for a in active if a["priority"] == "中"]
        streams[name]["top"] = (high + med)[:3]

    return streams

def generate_plan(analysis):
    """Generate today's plan from stream analysis"""
    plan = []

    # Stream 1: 论文
    papers = analysis["论文"]["top"]
    for p in papers:
        dim = p["dim"]
        title = p["title"]
        if "专著" in title or "Monograph" in title.lower():
            plan.append({
                "text": f"[专著] 继续撰写: {title[:40]}",
                "dot": "plan", "dim": dim
            })
        else:
            action = "推进撰写" if "撰写" in p["status"] else "推进研究"
            plan.append({
                "text": f"[论文] {action}: {title[:40]}",
                "dot": "plan", "dim": dim
            })

    # Stream 2: 专利
    patents = analysis["专利"]["top"]
    for p in patents:
        dim = p["dim"]
        title = p["title"]
        action = "推进撰写" if "撰写" in p["status"] else "推进构思"
        plan.append({
            "text": f"[专利] {action}: {title[:40]}",
            "dot": "plan", "dim": dim
        })

    # Stream 3: 项目指南
    guides = analysis["项目指南策划"]["top"]
    for g in guides:
        dim = g["dim"]
        title = g["title"]
        if "白皮书" in title:
            plan.append({
                "text": f"[白皮书] 持续更新: {title[:40]}",
                "dot": "plan", "dim": dim
            })
        elif "路线图" in title or "里程碑" in title:
            plan.append({
                "text": f"[路线图] 持续更新: {title[:40]}",
                "dot": "plan", "dim": dim
            })
        else:
            plan.append({
                "text": f"[指南] 持续推进: {title[:40]}",
                "dot": "plan", "dim": dim
            })

    # Cross-stream sync
    plan.append({
        "text": "[同步] 三条主线进度对齐：论文/专利/指南",
        "dot": "plan", "dim": "TCC+iNEST"
    })

    # Daily auto-research
    plan.append({
        "text": "[采集] 扫描昨日互联网+Get笔记，提取TCC/iNEST相关新研究",
        "dot": "plan", "dim": "TCC+iNEST"
    })

    return plan

def scan_yesterday_progress(daily_list):
    """Look at yesterday's activity and infer today's progress summary"""
    yesterday = (date.today() - timedelta(days=1)).isoformat()
    # Check if we have a crawler result
    progress = []

    # Check git activity (placeholder - would integrate with git log)
    progress.append({
        "text": f"看板自动更新：扫描昨日进展，生成今日待办",
        "dot": "done", "dim": "TCC+iNEST"
    })

    return progress

# ─── Main ───
def main():
    dry_run = "--dry-run" in sys.argv

    print("=" * 50)
    print(f"TCC x iNEST R&D Autopilot - {date.today().isoformat()}")
    print("=" * 50)

    # 1. Read current state
    entries = read_entries()
    print(f"\n[1] 读取 entries: {len(entries)} 条")

    # 2. Analyze
    analysis = analyze_entries(entries)
    for name, data in analysis.items():
        total = len(data["items"])
        active = len(data["active"])
        top = len(data["top"])
        print(f"    {name}: {total}条 | 活跃{active} | 优先{top}")

    # 3. Generate plan
    plan = generate_plan(analysis)
    print(f"\n[2] 生成今日计划: {len(plan)} 条")
    for p in plan:
        print(f"    [{p['dim']}] {p['text'][:60]}")

    # 4. Scan progress
    ver, daily = read_daily()
    progress = scan_yesterday_progress(daily)

    # 5. Update daily
    today_str = date.today().isoformat()
    # Remove existing today entry if present
    daily = [d for d in daily if d["date"] != today_str]

    new_entry = {
        "date": today_str,
        "type": "today",
        "progress": progress,
        "plan": plan
    }
    daily.insert(0, new_entry)

    if dry_run:
        print("\n[DRY RUN] 未写入。移除 --dry-run 以实际更新。")
        return

    new_ver = write_daily(daily)
    print(f"\n[3] 已更新 data.js → 版本: {new_ver}")
    print(f"    daily 条目: {len(daily)}")
    print("\n[OK] 刷新看板网页即可看到今日计划。")

if __name__ == "__main__":
    main()
